Repository Kotlin/dataframe, pull requests merged in 2022-12, with the labels that each got.

#169 Arrow writing
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/exceptions/TypeConverterNotFoundException.kt
  dataframe-arrow/build.gradle.kts
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowWriter.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowWriterImpl.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ConvertingMismatch.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowReading.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowReadingImpl.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowTypesMatching.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowWriting.kt
  dataframe-arrow/src/test/kotlin/ArrowKtTest.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/exampleEstimatesAssertions.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/examplesToWrite.kt
  docs/StardustDocs/topics/read.md
  docs/StardustDocs/topics/write.md
  gradle/libs.versions.toml
  tests/build.gradle.kts
  tests/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Write.kt
Labels: enhancement

#199 Backtick name bug
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
  plugins/symbol-processor/src/main/kotlin/org/jetbrains/dataframe/ksp/ExtensionsGenerator.kt
  plugins/symbol-processor/src/main/kotlin/org/jetbrains/dataframe/ksp/GetQualifiedNameOrThrow.kt
  plugins/symbol-processor/src/main/kotlin/org/jetbrains/dataframe/ksp/PropertyRenderer.kt
  plugins/symbol-processor/src/test/kotlin/org/jetbrains/dataframe/ksp/DataFrameSymbolProcessorTest.kt
Labels: bug

#200 Dataschema generic inheritance
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/MarkersExtractor.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/convertTo.kt
  plugins/symbol-processor/src/main/kotlin/org/jetbrains/dataframe/ksp/ExtensionsGenerator.kt
  plugins/symbol-processor/src/test/kotlin/org/jetbrains/dataframe/ksp/DataFrameSymbolProcessorTest.kt
Labels: bug, enhancement

#201 Add emptyDataFrame to documentation
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Create.kt
  docs/StardustDocs/topics/createDataFrame.md
Labels: documentation

#204 Sort grouped df
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/sort.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/DataFrameReceiver.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/sort.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/sortGroupedDataframe.kt
  core/src/test/resources/irisDataset.csv
Labels: bug

#205 Bugfix for NPE with fillNulls
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
Labels: bug, enhancement

#207 Support custom filling of missing columns in `convertTo`
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convertTo.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/columns/ColumnPath.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/exceptions/CellConversionException.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/exceptions/TypeConversionException.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/exceptions/TypeConverterNotFoundException.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convertTo.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/schema/Utils.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/convertTo.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowWriterImpl.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
  docs/StardustDocs/topics/convertTo.md
Labels: enhancement

#203 Added docs and clarifications to functional typealiases
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/aliases.kt
Labels: documentation

#209 Min kernel version fix
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/kernelUpdateMessages.kt
  gradle/libs.versions.toml
  plugins/dataframe-gradle-plugin/src/integrationTest/kotlin/org/jetbrains/dataframe/gradle/SchemaGeneratorPluginIntegrationTest.kt
Labels: bug, enhancement

#211 Don't print header record in csv if requested
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/csv.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/CsvTests.kt
Labels: enhancement, good first issue

#206 read -> unfold + Add documentation for unfold #159
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/toDataFrame.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/unfold.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  core/src/test/resources/dataframeContributors.json
  core/src/test/resources/kotlinContributors.json
  docs/StardustDocs/d.tree
  docs/StardustDocs/topics/collectionsInterop.md
  docs/StardustDocs/topics/modify.md
  docs/StardustDocs/topics/replace.md
  docs/StardustDocs/topics/unfold.md
Labels: enhancement
