Repository Kotlin/dataframe, pull requests merged in 2023-06, with the labels that each got.

#398 Fix missing articles and grammer in docs
  README.md
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.samples.api.Analyze.describe.html
  docs/StardustDocs/topics/ColumnSelectors.md
  docs/StardustDocs/topics/access.md
  docs/StardustDocs/topics/add.md
  docs/StardustDocs/topics/adjustSchema.md
  docs/StardustDocs/topics/apiLevels.md
  docs/StardustDocs/topics/cast.md
  docs/StardustDocs/topics/collectionsInterop.md
  docs/StardustDocs/topics/columnAccessorsApi.md
  docs/StardustDocs/topics/columnNames.md
  docs/StardustDocs/topics/columnTypes.md
  docs/StardustDocs/topics/concat.md
  docs/StardustDocs/topics/convert.md
  docs/StardustDocs/topics/convertTo.md
  docs/StardustDocs/topics/corr.md
  docs/StardustDocs/topics/count.md
  docs/StardustDocs/topics/create.md
  docs/StardustDocs/topics/createColumn.md
  docs/StardustDocs/topics/createDataFrame.md
  docs/StardustDocs/topics/cumSum.md
Labels: documentation

#403 withValue() -> with { value }
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/contains.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/DataRowApi.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/animals/AnimalsTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/contains.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/DataRowApi.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/animals/AnimalsTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.samples.api.DataRowApi.conditions.html
  docs/StardustDocs/topics/DataRow.md
  docs/StardustDocs/topics/convert.md
  docs/StardustDocs/topics/fill.md
  docs/StardustDocs/topics/update.md
  examples/idea-examples/titanic/src/main/kotlin/org/jetbrains/kotlinx/dataframe/examples/titanic/ml/titanic.kt
  examples/notebooks/puzzles/40 puzzles.ipynb
  examples/notebooks/titanic/Titanic.ipynb
Labels: documentation, invalid

#401 Fix: Jupyter compile-time DF type not recognized
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CodeGenerationTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterCodegenTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CodeGenerationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterCodegenTests.kt
  gradle/libs.versions.toml
Labels: bug, enhancement

#412 Add row functions to "operations overview" to make it comprehensive
  docs/StardustDocs/d.tree
  docs/StardustDocs/topics/DataRow.md
  docs/StardustDocs/topics/operations.md
  docs/StardustDocs/topics/rowStats.md
Labels: documentation
