Repository Kotlin/dataframe, pull requests merged in 2023-01, with the labels that each got.

#220 Describe how to control content cell limit from Jupyter Notebook
  docs/StardustDocs/topics/rendering.md
Labels: documentation

#213 Restore additional conversions from ValueColumn/ColumnGroup to FrameColumn
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convertTo.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/convertTo.kt
Labels: bug, enhancement

#221 Add nestedRowsLimit parameter to DisplayConfiguration
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt
Labels: enhancement, good first issue

#240 Fix new columns names generation during split operation (#224)
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/split.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/split.kt
Labels: enhancement, good first issue, invalid

#237 Cleaned up Access APIs docs
  docs/StardustDocs/topics/apiLevels.md
Labels: documentation
