Repository Kotlin/dataframe, pull requests merged in 2023-03, with the labels that each got.

#285 fixed 1password openapi example
  examples/idea-examples/json/src/main/kotlin/org/jetbrains/kotlinx/dataframe/examples/openapi/openApiApiGuru.kt
Labels: bug

#283 [Fix] Update.asFrame now takes filter into account.
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/update.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
Labels: bug, enhancement

#279 Rename Column typealias to AnyColumnReference
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/DataFrame.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/DataRow.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/aliases.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataFrameGet.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataRowApi.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/add.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/countDistinct.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/cumSum.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/group.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/groupBy.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/move.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/pivot.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/remove.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/select.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/toDataFrame.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/unfold.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ungroup.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCounts.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/values.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/with.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/aggregations.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/move.kt
Labels: invalid

#298 Hint about Kotlin Spark API in I/O docs
  docs/StardustDocs/topics/io.md
Labels: documentation

#293 Update Get started page
  docs/StardustDocs/d.tree
  docs/StardustDocs/r.list
  docs/StardustDocs/resources/movies.csv
  docs/StardustDocs/topics/gettingStarted.md
  docs/StardustDocs/topics/overview.md
  docs/StardustDocs/v.list
Labels: documentation

#299 Reduced number of top-level infix functions
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataColumnArithmetics.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/group.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
Labels: invalid

#301 fixed rowColExpression type in docs
  docs/StardustDocs/topics/convert.md
  docs/StardustDocs/topics/update.md
Labels: documentation

#305 Added `dropNaNs` function overloads
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Access.kt
  docs/StardustDocs/topics/drop.md
  docs/StardustDocs/topics/operations.md
Labels: enhancement, invalid

#311 Set logging to QUIET for generateDataFrameXXX tasks
  plugins/dataframe-gradle-plugin/src/main/kotlin/org/jetbrains/dataframe/gradle/SchemaGeneratorPlugin.kt
Labels: bug, invalid

#329 Windows build fix
  core/build.gradle.kts
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenDataFrame.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenRow.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenRowAndColumn.kt
  gradle/libs.versions.toml
Labels: bug
