Repository Kotlin/dataframe, pull requests merged in 2023-04, with the labels that each got.

#318 Column Selection DSL improvements
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/ColumnsContainer.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/columns/ColumnWithPath.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/DataFrameImpl.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/missing/MissingColumnGroup.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Access.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/ColumnsContainer.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/columns/ColumnWithPath.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/DataFrameImpl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/missing/MissingColumnGroup.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Access.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  docs/StardustDocs/topics/ColumnSelectors.md
Labels: enhancement

#343 Version bumps and dependency fixes
  build.gradle.kts
  core/build.gradle.kts
  dataframe-openapi/build.gradle.kts
  examples/idea-examples/json/build.gradle.kts
  examples/idea-examples/movies/build.gradle.kts
  examples/idea-examples/titanic/build.gradle.kts
  examples/idea-examples/youtube/build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  plugins/dataframe-gradle-plugin/build.gradle.kts
  settings.gradle.kts
  tests/build.gradle.kts
Labels: bug, enhancement, invalid, OpenAPI

#331 Columns Selection DSL KDocs and missing API overloads
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/ColumnsContainer.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/TypeConversions.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/add.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/constructors.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/AccessApi.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ColumnExpression.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DocumentationUrls.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/ColumnGroupWithParent.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/Utils.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Access.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/ColumnsContainer.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/TypeConversions.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/add.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/constructors.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/AccessApi.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ColumnExpression.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DocumentationUrls.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/ColumnGroupWithParent.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/Utils.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Access.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  docs/StardustDocs/topics/ColumnSelectors.md
  docs/StardustDocs/topics/split.md
Labels: KDocs

#357 Avoiding to use the URL-encoded path
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/common.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/common.kt
  data/jetbrains repositories.csv
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/DataFrameReadTest.kt
  plugins/symbol-processor/src/test/kotlin/org/jetbrains/dataframe/ksp/DataFrameSymbolProcessorTest.kt
Labels: bug, good first issue

#360 Avoiding to use the URL-encoded path - part 2
  core/build.gradle.kts
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Schemas.kt
  docs/StardustDocs/topics/gradle.md
  docs/StardustDocs/topics/gradleReference.md
  docs/StardustDocs/topics/read.md
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/SchemaGeneratorPluginTest.kt
Labels: bug

#226 Parse String column to nullable Double with correct locale
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/TypeConversions.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ParserTests.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
Labels: enhancement

#350 Variable width vector fix
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowWriterImpl.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/examplesToWrite.kt
  gradle/libs.versions.toml
Labels: bug, enhancement
