Repository Kotlin/dataframe, pull requests merged in 2024-09, with the labels that each got.

#846 Gradle bump to 8.10 and housekeeping
  build.gradle.kts
  core/build.gradle.kts
  dataframe-arrow/build.gradle.kts
  dataframe-excel/build.gradle.kts
  dataframe-jdbc/build.gradle.kts
  dataframe-openapi/build.gradle.kts
  examples/idea-examples/json/build.gradle.kts
  examples/idea-examples/movies/build.gradle.kts
  examples/idea-examples/titanic/build.gradle.kts
  examples/idea-examples/youtube/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  plugins/dataframe-gradle-plugin/build.gradle.kts
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/makeProject.kt
  plugins/expressions-converter/build.gradle.kts
  plugins/kotlin-dataframe/build.gradle.kts
  plugins/kotlin-dataframe/gradle/wrapper/gradle-wrapper.properties
  plugins/symbol-processor/build.gradle.kts
  tests/build.gradle.kts
Labels: infrastructure

#843 Enforcing kotlinx datetime bias
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/csv.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/parse.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ParserTests.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowWriterImpl.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowReadingImpl.kt
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowTypesMatching.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/exampleEstimatesAssertions.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/examplesToWrite.kt
  dataframe-excel/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/xlsx.kt
Labels: enhancement

#851 Compiler plugin update
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/add.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/addId.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/groupBy.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/map.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/move.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/analyzeRefinedCallShape.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/FunctionCallTransformer.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/ReturnTypeBasedReceiverInjector.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/add.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/addId.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/fillNulls.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/groupBy.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/map.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/move.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/update.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/interpret.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/utils/Names.kt
  plugins/kotlin-dataframe/testData/box/addDsl.kt
  plugins/kotlin-dataframe/testData/box/addId.kt
  plugins/kotlin-dataframe/testData/box/groupBy_refine.kt
  plugins/kotlin-dataframe/testData/box/mapToFrame.kt
  plugins/kotlin-dataframe/testData/box/moveToTop.kt
  plugins/kotlin-dataframe/testData/box/update.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#854 Version bumping GH actions
  .github/workflows/generated-sources-master.yml
  .github/workflows/generated-sources.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/main.yml
Labels: infrastructure

#853 Avoid 'expected: range(0, 32768)' exception when saving mixed data to Arrow
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowWriterImpl.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/examplesToWrite.kt
Labels: bug

#852 Allow reading ViewVarCharVector and ViewVarBinaryVector from Arrow files
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowReadingImpl.kt
Labels: enhancement

#856 Compiler plugin bugfixes
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/toDataFrame.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/explode.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/toDataFrame.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/interpret.kt
  plugins/kotlin-dataframe/testData/box/explode.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_dataSchema.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#861 Add Language annotations for better IDE experience
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/split.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
Labels: enhancement

#866 Revert "Generate fields in REPL for data schemas"
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/ReplCodeGeneratorImpl.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/ReplCodeGenTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/ReplCodeGeneratorImpl.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/ReplCodeGenTests.kt
Labels: bug

#868 Fix duplicated jvm signature
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/IrBodyFiller.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/interpret.kt
  plugins/kotlin-dataframe/testData/box/duplicatedSignature1.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#873 Fixed flaky jsonWrite test
  tests/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Write.kt
Labels: bug, tests

#882 Adding contracts for `Anycol.isValueColumn` etc. for smart-casting
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataColumnType.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colGroups.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/select.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCols.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/DataFrameReceiver.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convertTo.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/join.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/ColumnAccessorImpl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/tree/Utils.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
Labels: infrastructure

#885 Fix publish indexes docs
  .github/workflows/main.yml
Labels: infrastructure
