Repository Kotlin/dataframe, pull requests merged in 2024-06, with the labels that each got.

#714 Update README.md
  README.md
Labels: documentation

#725 File and URL names are used in JDK / suggested in IDE auto-import. Rename our classes to avoid conflict
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/guess.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/guess.kt
  dataframe-openapi/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/OpenApi.kt
Labels: invalid

#619 Column Selector Grammar in docs
  core/build.gradle.kts
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/all.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/allExcept.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/and.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/col.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colGroup.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colGroups.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/cols.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsAtAnyDepth.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsInGroups.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsOf.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsOfKind.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/columnNameFilters.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/columnRange.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/drop.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/first.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/frameCol.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/frameCols.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/last.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/rename.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/select.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/single.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/take.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCol.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCols.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/withoutNulls.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DslGrammarTemplateColumnsSelectionDsl.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/utils.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DslGrammarTemplateColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/utils.kt
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnGroupPartOfGrammar.ForHtml.html
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnSetPartOfGrammar.ForHtml.html
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.DefinitionsPartOfGrammar.html
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.PlainDslPartOfGrammar.html
  docs/StardustDocs/topics/ColumnSelectors.md
Labels: documentation, KDocs

#603 Replace Klaxon with kotlinx-serialization
  build.gradle.kts
  core/build.gradle.kts
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/readJson.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/writeJson.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/guess.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterHtmlRenderer.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/Utils.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ImageSerializationTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/RenderingTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/readJson.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/writeJson.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/guess.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterHtmlRenderer.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/Utils.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ImageSerializationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/RenderingTests.kt
  dataframe-openapi/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/DefaultReadOpenApiMethod.kt
  gradle/libs.versions.toml
  plugins/dataframe-gradle-plugin/build.gradle.kts
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/DataFrameReadTest.kt
  plugins/kotlin-dataframe/testData/box/read.fir.ir.txt
  plugins/kotlin-dataframe/testData/box/read.fir.txt
  plugins/kotlin-dataframe/testData/box/readCSV.fir.ir.txt
  plugins/kotlin-dataframe/testData/box/readCSV.fir.txt
  tests/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Write.kt
Labels: enhancement

#731 KDocs GH actions
  .editorconfig
  .github/workflows/generated-sources-master.yml
  .github/workflows/generated-sources.yml
  core/build.gradle.kts
  docs/StardustDocs/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnGroupPartOfGrammar.ForHtml.html
  docs/StardustDocs/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnSetPartOfGrammar.ForHtml.html
  docs/StardustDocs/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.DefinitionsPartOfGrammar.html
  docs/StardustDocs/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.PlainDslPartOfGrammar.html
  docs/StardustDocs/topics/ColumnSelectors.md
  gradle/scripts/pre-commit
Labels: KDocs

#737 Rename private properties with names matching library classes
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
Labels: invalid

#745 Add an option to read Excel cell values as a String regardless of their content type
  dataframe-excel/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/xlsx.kt
  dataframe-excel/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/XlsxTest.kt
  dataframe-excel/src/test/resources/mixed_column.xlsx
  docs/StardustDocs/topics/read.md
  tests/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Read.kt
Labels: enhancement

#747 Add castTo to help working with implicitly generated schemas in notebooks and plugin
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/cast.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  docs/StardustDocs/images/implicitlyGeneratedSchema.png
  docs/StardustDocs/topics/cast.md
Labels: enhancement

#749 [KDocs] auto preprocess only when publishing
  core/build.gradle.kts
Labels: KDocs
