Repository Kotlin/dataframe, pull requests merged in 2024-02, with the labels that each got.

#592 Ksp fix
  gradle/libs.versions.toml
  plugins/dataframe-gradle-plugin/src/main/kotlin/org/jetbrains/dataframe/gradle/ConvenienceSchemaGeneratorPlugin.kt
  plugins/dataframe-gradle-plugin/src/main/kotlin/org/jetbrains/dataframe/gradle/SchemaGeneratorPlugin.kt
  plugins/expressions-converter/src/org/jetbrains/kotlinx/dataframe/ExplainerIrTransformer.kt
Labels: bug

#597 generate "nullable properties" only where needed
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/ReplCodeGenTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/ReplCodeGenTests.kt
Labels: invalid

#590 Version bumps
  RELEASE_CHECK_LIST.md
  build.gradle.kts
  core/build.gradle.kts
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/DataColumn.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CodeGenerationTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterCodegenTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/RenderingTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/SampleNotebooksTests.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/HtmlRenderingTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/DataColumn.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CodeGenerationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterCodegenTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/RenderingTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/SampleNotebooksTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/HtmlRenderingTests.kt
  dataframe-arrow/build.gradle.kts
  dataframe-excel/build.gradle.kts
  dataframe-jdbc/build.gradle.kts
  dataframe-openapi/build.gradle.kts
  dataframe-openapi/src/test/kotlin/OpenApiTests.kt
  examples/idea-examples/json/build.gradle.kts
  examples/idea-examples/json/src/main/kotlin/org/jetbrains/kotlinx/dataframe/examples/openapi/openApiApiGuru.kt
  examples/idea-examples/movies/build.gradle.kts
  examples/idea-examples/titanic/build.gradle.kts
  examples/idea-examples/youtube/build.gradle.kts
  generator/build.gradle.kts
  generator/gradle.properties
  generator/src/main/kotlin/org/jetbrains/dataframe/keywords/GeneratorTask.kt
  generator/src/main/kotlin/org/jetbrains/dataframe/keywords/KeywordsGeneratorPlugin.kt
  gradle.properties
  gradle/libs.versions.toml
  plugins/dataframe-gradle-plugin/build.gradle.kts
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/EmbeddedServerRunners.kt
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/GradleRunnerDsl.kt
  plugins/expressions-converter/build.gradle.kts
  plugins/symbol-processor/build.gradle
  plugins/symbol-processor/src/test/kotlin/org/jetbrains/dataframe/ksp/EmbeddedServerRunners.kt
  settings.gradle.kts
  tests/build.gradle.kts
Labels: enhancement

#600 Updating docProcessor to 0.3.3
  gradle/libs.versions.toml
Labels: enhancement
