Repository Kotlin/dataframe, pull requests merged in 2024-12, with the labels that each got.

#967 Change toHTML rendering to allow custom HTML content inside cells and not just text
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/dataTypes/IMG.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CellRenderer.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/rendering/RenderingTests.kt
Labels: bug, enhancement

#965 Clarify the situation when generated extension property causes ClassCast or NPE exceptions
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/exceptions/ColumnTypeMismatchesColumnValuesException.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convert.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
Labels: bug

#984 org.jetbrains.kotlinx.dataframe.io.Csv clashes with CSV on windows...
  dataframe-csv/api/dataframe-csv.api
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/csv.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/tsv.kt
  dataframe-csv/src/main/resources/META-INF/services/org.jetbrains.kotlinx.dataframe.io.SupportedFormat
Labels: bug

#989 Miscellaneous 0.15 fixes
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/csv.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  dataframe-csv/README.md
  dataframe-csv/build.gradle.kts
  dataframe-csv/generated-sources/tmp
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/ListSink.kt
Labels: bug

#983 post-0.15 release documentation version bumps
  .github/workflows/main.yml
  README.md
  docs/StardustDocs/project.ihp
  docs/StardustDocs/v.list
Labels: documentation

#957 Add `df.properties()` function to improve visibility of generated API for typed column access
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/ColumnsContainer.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/ColumnsScope.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataFrameGet.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/CodeGeneratorImpl.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/ReplCodeGenTests.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/IrBodyFiller.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/TokenGenerator.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/utils/Names.kt
  plugins/kotlin-dataframe/testData/box/propertiesOrder.fir.txt
  plugins/kotlin-dataframe/testData/diagnostics/selectDuringTyping.fir.txt
  plugins/kotlin-dataframe/testData/diagnostics/toDataFrame_java.fir.txt
  plugins/symbol-processor/src/main/kotlin/org/jetbrains/dataframe/ksp/ExtensionsGenerator.kt
  plugins/symbol-processor/src/test/kotlin/org/jetbrains/dataframe/ksp/DataFrameSymbolProcessorTest.kt
Labels: enhancement

#979 [Compiler plugin] Add warning to avoid confusion with missing extension properties
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/ExpressionAnalysisAdditionalChecker.kt
  plugins/kotlin-dataframe/testData/diagnostics/targetOfCastIsNotDataSchema.fir.txt
  plugins/kotlin-dataframe/testData/diagnostics/targetOfCastIsNotDataSchema.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameDiagnosticTestGenerated.java
Labels: Compiler plugin

#968 Add kdoc about "Open in browser" from IDEA that helps to streamline working with HTML rendering
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt
Labels: KDocs

#1001 Bumping gradle to 8.11
  gradle/wrapper/gradle-wrapper.properties
Labels: infrastructure

#1004 `toDataFrame()` column order fix with `@ColumnName` annotations
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/schema/Utils.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/toDataFrame.kt
Labels: bug

#996 Keywords generator plugin: moved and fixed for Kotlin 2.1
  generator/src/main/kotlin/org/jetbrains/dataframe/keywords/KeywordsGeneratorPlugin.kt
  plugins/keywords-generator/README.md
  plugins/keywords-generator/build.gradle.kts
  plugins/keywords-generator/gradle.properties
  plugins/keywords-generator/settings.gradle.kts
  plugins/keywords-generator/src/main/kotlin/org/jetbrains/dataframe/keywords/EnumEntry.kt
  plugins/keywords-generator/src/main/kotlin/org/jetbrains/dataframe/keywords/KeywordsGeneratorAction.kt
  plugins/keywords-generator/src/main/kotlin/org/jetbrains/dataframe/keywords/KeywordsGeneratorPlugin.kt
  plugins/keywords-generator/src/main/kotlin/org/jetbrains/dataframe/keywords/KeywordsGeneratorTask.kt
  settings.gradle.kts
Labels: infrastructure
