Repository Kotlin/dataframe, pull requests merged in 2024-11, with the labels that each got.

#934 Specify slf4j-api instead of slf4j-simple.
  dataframe-jdbc/build.gradle.kts
  gradle/libs.versions.toml
Labels: infrastructure

#947 [Important Fix!] Parse started to removed unselected columns
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
Labels: bug

#942 [Compiler plugin] Propagate nullability in toDataFrame tree conversion
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/toDataFrame.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/interpret.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_customIterable.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_nullableList.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_nullableListSubtree.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_nullableSubtree.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: bug, Compiler plugin

#948 Add castTo(Function) overload for workflows that use compiler plugin
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/cast.kt
  plugins/kotlin-dataframe/testData/box/castTo_function.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: enhancement, Compiler plugin

#918 [Compiler plugin] Setup call transformer pipeline to handle (...) -> DataRow functions
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/FunctionCallTransformer.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/ReturnTypeBasedReceiverInjector.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/read.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/readJsonStr_datarow.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#944 Render FormattedFrame stored inside columns as HTML
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/rendering/RenderingTests.kt
Labels: enhancement

#950 Version bump KtLint to 1.4.1
  .editorconfig
  build.gradle.kts
Labels: infrastructure

#924 Make it clear that dataframes are immutable
  docs/StardustDocs/topics/overview.md
Labels: documentation

#949 Compiler plugin read improvements
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/flatten.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/read.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/flatten.kt
  plugins/kotlin-dataframe/testData/box/readExcel.kt
  plugins/kotlin-dataframe/testData/box/readExcel_stringColumns.kt
  plugins/kotlin-dataframe/testData/box/read_localFile.kt
  plugins/kotlin-dataframe/testResources/sample.xls
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#951 [Compiler plugin] Support valueCounts
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCounts.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/ExpectedArgumentDelegates.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/add.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/convert.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/dataFrameOf.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/insert.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/read.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/rename.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/stdlib.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/valueCounts.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/valueCounts.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#952 Add examples for rename
  core/src/main/resources/table.css
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Modify.kt
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.samples.api.Modify.rename.html
  docs/StardustDocs/snippets/org.jetbrains.kotlinx.dataframe.samples.api.Modify.renameExpression.html
  docs/StardustDocs/topics/rename.md
Labels: documentation

#972 Full `BigInteger` support
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataColumnArithmetics.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/TypeUtils.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/Utils.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/convert.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/describe.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/csv.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/readDelim.kt
Labels: enhancement

#976 small fix for file clash at impl/io/readDelim.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/readDelim.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/writeDelim.kt
Labels: bug
