Repository Kotlin/dataframe, pull requests merged in 2024-03, with the labels that each got.

#618 Fixes in resize-iframes.js
  docs/StardustDocs/cfg/resize-iframes.js
Labels: bug, documentation

#616 Fix for mac-os permissions pre-commit
  core/build.gradle.kts
Labels: bug

#621 prevent Klaxon from using default reflective serializer
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/writeJson.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/writeJson.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
Labels: bug

#548 migrate Titanic.ipynb to Kandy
  examples/notebooks/titanic/Titanic.ipynb
Labels: examples

#631 added toDataFrame for float- and double iterables
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/toDataFrame.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/toDataFrame.kt
Labels: bug, enhancement
