Repository Kotlin/dataframe, pull requests merged in 2024-04, with the labels that each got.

#617 then operation in pivot column selection DSL inside aggregate
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/pivot.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/PivotInAggregateImpl.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/pivot.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/pivot.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/PivotInAggregateImpl.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/pivot.kt
Labels: enhancement

#628 Allow any ArrowReader implementation to be use for reading Arrow data #627
  dataframe-arrow/build.gradle.kts
  dataframe-arrow/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/arrowReadingImpl.kt
  dataframe-arrow/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/ArrowKtTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#643 add random parameter to shuffle
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/shuffle.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/shuffle.kt
Labels: enhancement

#652 Updated parse documentation
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/parse.kt
  docs/StardustDocs/topics/parse.md
Labels: documentation

#653 Updated split documentation
  docs/StardustDocs/topics/split.md
Labels: documentation

#641 Fix #640: Jupyter integration conflicts with variable type converters from other integrations
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterCodegenTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/JupyterCodegenTests.kt
Labels: bug
