Repository Kotlin/dataframe, pull requests merged in 2025-04, with the labels that each got.

#1114 [Compiler plugin] Support df.asGroupBy
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/typeConversions.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/groupBy.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/interpret.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/asGroupBy.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#1119 Overhaul for std
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Defaults.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/max.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/mean.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/min.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/std.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/sum.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/aggregators/Aggregators.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/corr.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/basicStats.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/mean.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/std.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/stdMean.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/max.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/min.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/std.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/sum.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataRowTests.kt
Labels: enhancement

#1128 [Compiler plugin] Remove outdated code
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/insert.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/convert.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/insert.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
Labels: Compiler plugin

#1127 [Compiler plugin] Support `unfold`
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/unfold.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/unfold.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/unfold.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/toDataFrame.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/unfold.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/unfold.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#1131 added small note in add docs to link to insert
  docs/StardustDocs/topics/add.md
Labels: documentation

#1145 [Compiler plugin] Support SingleColumn.select
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/select.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/select.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/csDsl/select.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#1144 Add a constructor to create a nested dataframe from columns inplace
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/constructors.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Create.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
  docs/StardustDocs/topics/createDataFrame.md
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/FunctionCallTransformer.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/ReturnTypeBasedReceiverInjector.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/dataFrameOf.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/utils/Names.kt
  plugins/kotlin-dataframe/testData/box/columnOf_nested.kt
  plugins/kotlin-dataframe/testData/box/dataFrameOf_nested.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: enhancement

#1149 Percentile
  core/api/core.api
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/median.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/percentile.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/aggregators/Aggregators.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/describe.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/median.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/percentile.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/quantile.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/util/deprecationMessages.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/describe.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/QuantileTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/percentile.kt
  gradle/libs.versions.toml
Labels: enhancement

#1152 CumSum
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Defaults.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/cumSum.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/aggregators/Aggregators.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/aggregators/inputHandlers/NumberInputHandler.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/cumsum.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/sum.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/cumsum.kt
  examples/notebooks/dev/netflix/netflix.ipynb
Labels: enhancement

#1139 [Compiler plugin] join operations support
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/and.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/join.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/joinWith.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/none.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/columns/constructors.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/join.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/columns/ColumnsList.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/join.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/joinDsl.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/joinWith.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/select.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/joinKinds.kt
  plugins/kotlin-dataframe/testData/box/joinWithKinds.kt
  plugins/kotlin-dataframe/testData/box/joinWith_duplicateColumnGroups.kt
  plugins/kotlin-dataframe/testData/box/join_matchColumnGroups.kt
  plugins/kotlin-dataframe/testData/box/join_mergeColumnGroups.kt
  plugins/kotlin-dataframe/testData/testUtils.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#1163 Simplifies some dependencies, especially jupyter
  build.gradle.kts
  dataframe-arrow/build.gradle.kts
  dataframe-csv/build.gradle.kts
  dataframe-jupyter/build.gradle.kts
  dataframe-jupyter/src/main/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/Integration.kt
  plugins/dataframe-gradle-plugin/build.gradle.kts
  plugins/symbol-processor/build.gradle.kts
  tests/build.gradle.kts
Labels: infrastructure

#1164 json module docs
  docs/StardustDocs/topics/gettingStartedGradleAdvanced.md
  docs/StardustDocs/topics/parse.md
  docs/StardustDocs/topics/read.md
Labels: documentation
