Repository Kotlin/dataframe, pull requests merged in 2025-03, with the labels that each got.

#1084 Prepare plugin to be moved to Kotlin repository
  core/api/core.api
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/annotations/Plugin.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/MarkersExtractor.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/csv.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/guess.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  dataframe-excel/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/xlsx.kt
  plugins/kotlin-dataframe/build.gradle.kts
  plugins/kotlin-dataframe/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/FirDataFrameComponentRegistrar.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/ExpressionAnalysisAdditionalChecker.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/FunctionCallTransformer.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/IrBodyFiller.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/KotlinTypeFacade.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/read.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/toDataFrame.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/data/toPluginDataFrameSchema.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/utils/Names.kt
  plugins/kotlin-dataframe/testData/box/castTo.kt
  plugins/kotlin-dataframe/testData/box/explodeDataFrame.kt
  plugins/kotlin-dataframe/testData/box/join.kt
  plugins/kotlin-dataframe/testData/box/propertiesOrder.fir.txt
  plugins/kotlin-dataframe/testData/box/propertiesOrder.kt
  plugins/kotlin-dataframe/testData/box/read.kt
  plugins/kotlin-dataframe/testData/box/readCSV.kt
  plugins/kotlin-dataframe/testData/box/readExcel.kt
  plugins/kotlin-dataframe/testData/box/readExcel_stringColumns.kt
  plugins/kotlin-dataframe/testData/box/readJson.kt
  plugins/kotlin-dataframe/testData/box/readJsonStr_const.kt
  plugins/kotlin-dataframe/testData/box/readJsonStr_datarow.kt
  plugins/kotlin-dataframe/testData/box/readJsonStr_localProperty.kt
  plugins/kotlin-dataframe/testData/box/readJsonStr_memberProperty.kt
  plugins/kotlin-dataframe/testData/box/read_localFile.kt
  plugins/kotlin-dataframe/testData/box/trimIndent.kt
  plugins/kotlin-dataframe/testData/box/trimMargin.kt
  plugins/kotlin-dataframe/testResources/achievements_all.json
  plugins/kotlin-dataframe/testResources/sample.xls
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
  plugins/kotlin-dataframe/tests/org/jetbrains/kotlin/fir/dataframe/services/ExtensionRegistrarConfigurators.kt
Labels: infrastructure, Compiler plugin

#1087 Post Java 11 version bumps
  .github/workflows/generated-sources-master.yml
  .github/workflows/generated-sources.yml
  CONTRIBUTING.md
  build.gradle.kts
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/json.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/BasicMathTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/std.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/animals/AnimalsTests.kt
  dataframe-openapi-generator/src/test/kotlin/OpenApiTests.kt
  gradle/libs.versions.toml
  plugins/keywords-generator/build.gradle.kts
Labels: infrastructure

#1089 Fixed `valuesAreComparable()` and tests
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/DataColumnType.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTests.kt
Labels: bug

#1088 [Compiler plugin] Support DataFrame.aggregate
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/DataFrame.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/groupBy.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/loadInterpreter.kt
  plugins/kotlin-dataframe/testData/box/aggregateDataFrame.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: Compiler plugin

#1094 Disable large logs in tests for `FastDoubleParser`
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/FastDoubleParser.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/FastDoubleParserTests.kt
  core/src/test/resources/simplelogger.properties
  dataframe-csv/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/DelimCsvTsvTests.kt
  dataframe-csv/src/test/resources/simplelogger.properties
Labels: infrastructure

#1096 Publish compiler plugin :core subset from another module
  core/build.gradle.kts
  dataframe-compiler-plugin-core/README.md
  dataframe-compiler-plugin-core/build.gradle.kts
  plugins/kotlin-dataframe/build.gradle.kts
  settings.gradle.kts
Labels: infrastructure

#1106 Set version to 1.0.0
  gradle.properties
Labels: infrastructure

#1110 Ensure a predictable order of columns after aggregation of `GroupBy`
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/typeConversions.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/io/PlaylistJsonTest.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/testSets/person/DataFrameTreeTests.kt
Labels: Compiler plugin
