Repository Kotlin/dataframe, pull requests merged in 2025-07, with the labels that each got.

#1312 Flatten navigation of Modify operations
  docs/StardustDocs/d.tree
  docs/StardustDocs/topics/add.md
  docs/StardustDocs/topics/addRemove.md
  docs/StardustDocs/topics/append.md
  docs/StardustDocs/topics/cast.md
  docs/StardustDocs/topics/concat.md
  docs/StardustDocs/topics/convert.md
  docs/StardustDocs/topics/convertTo.md
  docs/StardustDocs/topics/distinct.md
  docs/StardustDocs/topics/drop.md
  docs/StardustDocs/topics/duplicate.md
  docs/StardustDocs/topics/explode.md
  docs/StardustDocs/topics/fill.md
  docs/StardustDocs/topics/filter.md
  docs/StardustDocs/topics/flatten.md
  docs/StardustDocs/topics/group.md
  docs/StardustDocs/topics/insert.md
  docs/StardustDocs/topics/join.md
  docs/StardustDocs/topics/map.md
  docs/StardustDocs/topics/merge.md
  docs/StardustDocs/topics/move.md
  docs/StardustDocs/topics/parse.md
  docs/StardustDocs/topics/remove.md
  docs/StardustDocs/topics/rename.md
  docs/StardustDocs/topics/reorder.md
  docs/StardustDocs/topics/replace.md
  docs/StardustDocs/topics/reverse.md
  docs/StardustDocs/topics/select.md
  docs/StardustDocs/topics/shuffle.md
  docs/StardustDocs/topics/sortBy.md
  docs/StardustDocs/topics/split.md
  docs/StardustDocs/topics/toList.md
  docs/StardustDocs/topics/update.md
  docs/StardustDocs/topics/updateConvert.md
Labels: documentation

#1333 add missed compiler annotations for update
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
Labels: Compiler plugin

#1311 generateCode.kt refactor, KDocs, documentation fixes, and tests
  core/api/core.api
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/generateCode.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/Marker.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/util/deprecationMessages.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/generateCode.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/Marker.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DocumentationUrls.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/util/deprecationMessages.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  docs/StardustDocs/resources/api/generate_docs/notebook_test_generate_docs_1.html
  docs/StardustDocs/resources/api/rename/notebook_test_rename_3.html
  docs/StardustDocs/resources/api/rename/notebook_test_rename_4.html
  docs/StardustDocs/resources/api/rename/notebook_test_rename_5.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_10.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_11.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_12.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_13.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_14.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_3.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_4.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_5.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_6.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_7.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_8.html
  docs/StardustDocs/topics/concepts/DataSchemaGenerationMethods.md
  examples/idea-examples/unsupported-data-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/examples/exposed/tables.kt
Labels: documentation, enhancement, KDocs, tests
