Repository Kotlin/dataframe, pull requests merged in 2025-05, with the labels that each got.

#1165 statistics documentation update
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/NumberTypeUtils.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/samples/api/Analyze.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/statistics/sum.kt
  docs/StardustDocs/d.tree
  docs/StardustDocs/topics/DataRow.md
  docs/StardustDocs/topics/columnStatistics.md
  docs/StardustDocs/topics/mean.md
  docs/StardustDocs/topics/median.md
  docs/StardustDocs/topics/minmax.md
  docs/StardustDocs/topics/numberUnification.md
  docs/StardustDocs/topics/percentile.md
  docs/StardustDocs/topics/std.md
  docs/StardustDocs/topics/sum.md
  docs/StardustDocs/topics/summaryStatistics.md
  docs/StardustDocs/topics/valueCounts.md
Labels: documentation

#1177 Remove logging from the API used for the compiler plugin
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/aggregation/aggregators/inputHandlers/NumberInputHandler.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/mean.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/median.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/percentile.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/quantile.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/math/std.kt
Labels: bug, Compiler plugin

#1154 Generate fields for markers in REPL so compiler plugin can extract the schema
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/codeGen/ReplCodeGeneratorImpl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/schema/DataFrameSchemaImpl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/ColumnSchema.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/schema/DataFrameSchema.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/CodeGenerationTests.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/codeGen/ReplCodeGenTests.kt
  dataframe-jupyter/src/test/kotlin/org/jetbrains/kotlinx/dataframe/jupyter/CodeGenerationTests.kt
Labels: Compiler plugin

#1200 Number unification docs
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/UnifyingNumbers.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/utils.kt
  core/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/NumberTypeUtils.kt
  core/generated-sources/src/test/kotlin/org/jetbrains/kotlinx/dataframe/types/UtilTests.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/UnifyingNumbers.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/utils.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DelimParams.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/io/readDelim.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readCsv.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readCsvStr.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readDelim.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readDelimStr.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readTsv.kt
  dataframe-csv/generated-sources/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readTsvStr.kt
  docs/StardustDocs/resources/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnGroupPartOfGrammar.ForHtml.html
  docs/StardustDocs/resources/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnSetPartOfGrammar.ForHtml.html
  docs/StardustDocs/resources/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.DefinitionsPartOfGrammar.html
  docs/StardustDocs/resources/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.PlainDslPartOfGrammar.html
  docs/StardustDocs/resources/snippets/kdocs/org.jetbrains.kotlinx.dataframe.documentation.UnifyingNumbers.Graph.html
  docs/StardustDocs/topics/numberUnification.md
  gradle/libs.versions.toml
Labels: documentation

#1207 Prepare update and implode operations for compiler plugin support
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/implode.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
Labels: Compiler plugin

#1208 Minor fixes for the docs
  docs/StardustDocs/topics/Compiler-Plugin.md
  docs/StardustDocs/topics/dataSchema.md
  docs/StardustDocs/topics/staticInterpretation.md
Labels: documentation

#1209 Update README.md
  README.md
Labels: documentation

#1211 Update Gradle plugin docs and fix hardcoded versions
  docs/StardustDocs/d.tree
  docs/StardustDocs/topics/Compiler-Plugin.md
  docs/StardustDocs/topics/gettingStarted/gettingStartedGradle.md
  docs/StardustDocs/topics/gradleReference.md
  docs/StardustDocs/v.list
Labels: documentation
