Repository Kotlin/dataframe, pull requests merged in 2025-06, with the labels that each got.

#1226 Adding links to column selectors in docs
  docs/StardustDocs/topics/add.md
  docs/StardustDocs/topics/convert.md
  docs/StardustDocs/topics/corr.md
  docs/StardustDocs/topics/cumSum.md
  docs/StardustDocs/topics/distinct.md
  docs/StardustDocs/topics/drop.md
  docs/StardustDocs/topics/explode.md
  docs/StardustDocs/topics/fill.md
  docs/StardustDocs/topics/filter.md
  docs/StardustDocs/topics/flatten.md
  docs/StardustDocs/topics/gather.md
  docs/StardustDocs/topics/group.md
  docs/StardustDocs/topics/groupBy.md
  docs/StardustDocs/topics/implode.md
  docs/StardustDocs/topics/inferType.md
  docs/StardustDocs/topics/mean.md
  docs/StardustDocs/topics/median.md
  docs/StardustDocs/topics/merge.md
  docs/StardustDocs/topics/minmax.md
  docs/StardustDocs/topics/move.md
  docs/StardustDocs/topics/percentile.md
  docs/StardustDocs/topics/pivot.md
  docs/StardustDocs/topics/remove.md
  docs/StardustDocs/topics/rename.md
  docs/StardustDocs/topics/reorder.md
  docs/StardustDocs/topics/replace.md
  docs/StardustDocs/topics/reshape.md
  docs/StardustDocs/topics/sortBy.md
  docs/StardustDocs/topics/split.md
  docs/StardustDocs/topics/std.md
  docs/StardustDocs/topics/sum.md
  docs/StardustDocs/topics/summaryStatistics.md
  docs/StardustDocs/topics/unfold.md
  docs/StardustDocs/topics/ungroup.md
  docs/StardustDocs/topics/update.md
  docs/StardustDocs/topics/valueCounts.md
  docs/StardustDocs/topics/values.md
Labels: documentation

#1232 Use `DayOfWeek.isoDayNumber` instead of `DayOfWeek.value` in `DateTests.kt`.
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/puzzles/DateTests.kt
Labels: tests

#1285 Bump gradle to 8.14.2
  build.gradle.kts
  core/build.gradle.kts
  dataframe-arrow/build.gradle.kts
  dataframe-csv/build.gradle.kts
  dataframe-excel/build.gradle.kts
  dataframe-jdbc/build.gradle.kts
  dataframe-json/build.gradle.kts
  dataframe-jupyter/build.gradle.kts
  dataframe-openapi-generator/build.gradle.kts
  docs/StardustDocs/resources/api/generate_docs/notebook_test_generate_docs_1.html
  docs/StardustDocs/resources/api/rename/notebook_test_rename_3.html
  docs/StardustDocs/resources/api/rename/notebook_test_rename_4.html
  docs/StardustDocs/resources/api/rename/notebook_test_rename_5.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_10.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_11.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_12.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_13.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_14.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_3.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_4.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_5.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_6.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_7.html
  docs/StardustDocs/resources/guides/quickstart/notebook_test_quickstart_8.html
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  plugins/dataframe-gradle-plugin/src/main/kotlin/org/jetbrains/dataframe/gradle/SchemaGeneratorPlugin.kt
  plugins/dataframe-gradle-plugin/src/test/kotlin/org/jetbrains/dataframe/gradle/makeProject.kt
  plugins/expressions-converter/build.gradle.kts
  plugins/expressions-converter/src/org/jetbrains/kotlinx/dataframe/ExplainerIrTransformer.kt
  plugins/kotlin-dataframe/build.gradle.kts
  settings.gradle.kts
  tests/build.gradle.kts
Labels: infrastructure
