Repository Kotlin/dataframe, pull requests merged in 2025-01, with the labels that each got.

#994 Documentation mention of experimental dataframe-csv
  docs/StardustDocs/topics/read.md
Labels: documentation

#1009 Convert `DataFrameHtmlData` to normal class
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/html.kt
Labels: bug

#1015 Documentation for date-time pattern
  docs/StardustDocs/topics/read.md
Labels: documentation

#1017 Kodex 0.4.2
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DslGrammarTemplateColumnsSelectionDsl.kt
  dataframe-csv/build.gradle.kts
  gradle/libs.versions.toml
Labels: KDocs, infrastructure

#1018 Renaming all KoDEx documentation arguments to SCREAMING_SNAKE_CASE
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/Nulls.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/all.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/allExcept.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/and.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/col.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colGroup.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colGroups.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/cols.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsAtAnyDepth.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsInGroups.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsOf.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/colsOfKind.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/columnNameFilters.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/columnRange.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/distinct.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/drop.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/expr.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/filter.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/first.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/frameCol.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/frameCols.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/last.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/none.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/rename.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/select.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/simplify.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/single.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/take.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/update.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCol.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/valueCols.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/withoutNulls.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/AccessApi.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/CommonTakeAndDropDocs.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/CommonTakeAndDropWhileDocs.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DslGrammarTemplateColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenColumn.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenDataFrame.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenRow.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/ExpressionsGivenRowAndColumn.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/SelectingColumns.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/SelectingRows.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/TakeAndDropColumnsSelectionDslGrammar.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/CommonReadDelimDocs.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/CommonWriteDelimDocs.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/documentation/DelimParams.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readCsv.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readCsvStr.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readDelim.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readDelimStr.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readTsv.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/readTsvStr.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/toCsvStr.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/toDelimStr.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/toTsvStr.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/writeCsv.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/writeDelim.kt
  dataframe-csv/src/main/kotlin/org/jetbrains/kotlinx/dataframe/io/writeTsv.kt
Labels: KDocs, infrastructure

#1030 Removing `exceptNew`
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/ColumnsSelectionDsl.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/allExcept.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/allExcept.kt
  docs/StardustDocs/snippets/kdocs/org.jetbrains.kotlinx.dataframe.api.ColumnsSelectionDsl.DslGrammar.ColumnGroupPartOfGrammar.ForHtml.html
  docs/StardustDocs/topics/ColumnSelectors.md
Labels: bug, enhancement

#1034 Allow running Gradle tasks with -PskipKodex to publish locally faster
  CONTRIBUTING.md
  KDOC_PREPROCESSING.md
  core/build.gradle.kts
Labels: KDocs, infrastructure

#990 Sort df.compileTimeSchema() columns according to df.schema() so they're easier to compare
  core/api/core.api
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/api/schema.kt
  core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/schema.kt
  core/src/test/kotlin/org/jetbrains/kotlinx/dataframe/api/schema.kt
Labels: enhancement

#1043 [Compiler plugin] Fix toDataFrame for different visibilities
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/impl/api/toDataFrame.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_local_class.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_private_class.kt
  plugins/kotlin-dataframe/testData/box/toDataFrame_private_properties.kt
  plugins/kotlin-dataframe/tests-gen/org/jetbrains/kotlin/fir/dataframe/DataFrameBlackBoxCodegenTestGenerated.java
Labels: bug, Compiler plugin

#1041 Map transformed calls and generated properties to their origin
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/CallShapeAttribute.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/FunctionCallTransformer.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/TokenGenerator.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/extensions/TopLevelExtensionsGenerator.kt
  plugins/kotlin-dataframe/src/org/jetbrains/kotlinx/dataframe/plugin/utils/firFactories.kt
Labels: bug, Compiler plugin
